### ISSUE TITLE
healthcheck

### ISSUE THREAD

**Issue by brettmc** [disaster37/activemq#25]
this is a feature request.
docker 1.12 added a [HEALTHCHECK](https://docs.docker.com/engine/reference/builder/#/healthcheck) command, which would be a useful feature IMO, particularly if deploying activemq into a docker swarm...

I've had a play with trying to run something from a shell which might indicate a working activemq instance (I'm imagining that listing brokers and getting a non-zero response, or putting a message onto a queue and reading it back) - but I haven't had any success yet.

**Comment by pprazzi** [comment]
I had limited success using netcat

```
    healthcheck:
      test: nc -z localhost 8311 || exit 1
      interval: 20s
      timeout: 10s
      retries: 10
```

where 8311 is to port to check

However, this seems to trigger 

`org.apache.activemq.broker.TransportConnection.Transport - Transport failed: java.io.EOFException` INFO messages

because the client connection is not closed properly
