### ISSUE TITLE
websocket config not working

### ISSUE THREAD

**Issue by Javiseeker** [disaster37/activemq#44]
Left Default settings and created this docker-compose.yml

```
  broker:
    image: webcenter/activemq
    container_name: "activemq_broker"
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61614:61614"
      - "61616:61616"
    environment:
      ACTIVEMQ_NAME: amq
      ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT: 'True'
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    volumes:
      - /container_data/activemq/data:/data/activemq
      - /container_data/activemq/log:/var/log/activemq
```

Somehow I can't receive mqtt messages via Websocket. I can succesfully receive them via mqtt in my backend, but not in my angular application via Websocket. I already had an activemq broker working before and tried passing its own activemq.xml conf file as follows:
```
    volumes:
      - /container_data/activemq/data:/data/activemq
      - /container_data/activemq/log:/var/log/activemq
      - ./broker-config:/opt/activemq/conf
```
But this volume simply crashes the broker. ThenI noticed that it's warned to do this:

""If you overload the config, don't forget to disable confd or change the template instead to change activemq config /opt/confd/etc/templates.""

 but I don't understand what else to do.. Help please!
